- python=3.8
- jupyterthemes==0.20.0
- tk==0.1.0
- python3-tk # Ubuntu package for tkinter support
- ipywidgets==7.7.2
- xarray==2022.12.0
- rioxarray==0.13.3
- rasterio==1.3.4
- numpy==1.26.2
- spyndex==0.2.0
- pandas==1.5.3
- matplotlib==3.5.1
- seaborn==0.12.2
- ray==2.7.0
- tqdm==4.64.1
